server:
  port: 9000

spring:
  application:
    name: authentication

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
    registerWithEureka: true
    fetchRegistry: true
    should-unregister-on-shutdown: true